---
- name: Deploy a basic httpd server
  hosts: all
  become: yes

  tasks:
   - name: install httpd and firewalld
     yum:
       name: "{{ item }}"
       state: present
     loop:
       - httpd
       - firewalld

   - name: template out the index page
     template:
       src: index.j2
       dest: /var/www/html/index.html
       mode: 0644
       owner: root
       group: root

   - name: template out the web server files
     copy:
       src: w3_page_files
       dest: /var/www/html/
       mode: 0755
       owner: root
       group: root

   - name: start and enable firewalld
     service:
       name: firewalld
       state: started
       enabled: yes

   - name: add firewalld rules for httpd
     firewalld:
       service: http
       state: enabled

   - name: restart httpd
     service:
       name: httpd
       state: restarted
