---
- name: Deploy a basic httpd server
  hosts: all
  become: yes

  tasks:
   - name: install httpd
     yum:
       name: httpd
       state: present

  
   - name: template out the index page
     template:
       src: index.j2
       dest: /var/www/html/index.html
       mode: 0644
       owner: root
       group: root

   - name: start and enable firewalld
     servce:
       name: firewalld
       state: started
       enabled: yes

   - name: add firewalld rules for httpd
     firewalld:
       service: http
       state: enabled


   - name: restart httpd
     service:
       name: httpd
       state: restarted
